version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./api:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  db:
    image: postgres:15
    container_name: pg-docker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
